amcl:
  ros__parameters:
    use_sim_time: false

    # Frames
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link

    # Topics
    scan_topic: /scan

    # Particle filter
    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99

    # Motion model
    robot_model_type: nav2_amcl::DifferentialMotionModel
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2

    # Sensor model
    laser_model_type: likelihood_field
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0

    # Update / resample
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1

    # TF
    tf_broadcast: true
    transform_tolerance: 0.2
