hsv_range:
  lower:
    h: 0
    s: 60
    v: 40
  upper:
    h: 40
    s: 255
    v: 255

morphology:
  kernel_size: 5
  iterations: 1

detection:
  min_area: 600.0

apple:
  min_circularity: 0.62
  aspect_ratio_min: 0.7
  aspect_ratio_max: 1.45
  min_area: 800.0

banana:
  max_circularity: 0.40
  aspect_ratio_min: 1.9
  aspect_ratio_max: 6.0
  min_area: 600.0

action_mapping:
  apple: "right_turn"     # 右转
  banana: "left_turn"     # 左转