hsv_range:
  lower:
    h: 0
    s: 50
    v: 60
  upper:
    h: 50
    s: 255
    v: 255

morphology:
  kernel_size: 5

detection:
  min_area: 600.0

apple:
  min_circularity: 0.60
  aspect_ratio_min: 0.75
  aspect_ratio_max: 1.40
  min_area: 800.0

banana:
  max_circularity: 0.45
  aspect_ratio_min: 1.8
  aspect_ratio_max: 6.5
  min_area: 600.0

action_mapping:
  apple: "right_turn"     # 右转
  banana: "left_turn"     # 左转  